apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mcdj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-mcdj@sha256:6b6ccb3f2d3a5f53d650c02034e31ac7b0125128b0c65b209f9ea287876088b1
        name: my-nodejs
        resources: {}
status: {}
